cp _build/bbs/bbs /opt/wwiv
cp _build/wwivd/wwivd /opt/wwiv
cp _build/wwivconfig/wwivconfig /opt/wwiv
cp _build/network/network /opt/wwiv
cp _build/network/network /opt/wwiv
cp _build/network1/network1 /opt/wwiv
cp _build/network3/network3 /opt/wwiv
cp _build/networkb/networkb /opt/wwiv
cp _build/networkc/networkc /opt/wwiv
cp _build/networkt/networkt /opt/wwiv
